In [3]:
import numpy as np


In [9]:
'''
基本介绍
参考：https://www.jianshu.com/p/358948fbbc6e

Numpy的数组类被叫做 ndarray, 当然，它还有另一个别名 array 。
注意：numpy.array 不同于 python 标准库里的 array.array. 
后者只能处理一维的数组且提供的函数比较少
ndarray.ndim  返回数组中轴的数量
ndarray.shape 返回数组的维度。它以正整数的元组形式返回每一个轴的长度。
                比如对于一个n行m列的矩阵， shape 就为 （n,m）.
ndarray.reshape（i，j，k） 生成新形状（不改变原来）

ndarray.size  返回数组所有元素的数目。它是shape元素的乘积
ndarray.resize(i,j,k) 生成新形状且改变原来 

ndarray.dtype 返回数组中元素的数据类型
ndarray.itemsize 返回数组中元素的字节数
'''
print()

In [4]:
test=np.arange(15).reshape(3,5)
print(test)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
type(test)

numpy.ndarray

In [7]:
test.shape

(3, 5)

In [8]:
test.ndim

2

In [13]:
'''
数组的创建

'''
#python list tuple
#一维
a=[1,2,3]
A=np.array(a) #或A=np.array([1,2,3])  
#多维 
b=[(1,2,3),(4,5,6)]
#顺便指定数据类型
B=np.array(b,dtype=float)
print(A)
print(B)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]


In [84]:
#初始化数组
C=np.zeros((2,3))
D=np.ones((2,3))
E=np.empty((3,4))
K=100*np.random.random((3,3))
print(C)
print(D)
print(E)
print(K)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313]
 [1.90979621e-313 2.33419537e-313 2.75859453e-313 3.18299369e-313]
 [3.60739285e-313 4.03179200e-313 4.45619116e-313 4.88059032e-313]]
[[82.0634072  88.16013021 66.15432138]
 [88.84916225 95.93511089 48.46594916]
 [44.18140358 98.21261964 96.45629241]]


In [18]:
#生成数列
#起始值，结束值（取不到），间隔值
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [19]:
#linespace 
#起始值，结束值（取的到），数列长度
np.linspace( 0, 2, 9 )  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
'''
基本操作
'''

#元素按位 加 减 乘 除
print(np.sin(a))
A**2

[0.84147098 0.90929743 0.14112001]


array([1, 4, 9], dtype=int32)

In [37]:
#矩阵乘法 A dot B A的行=B的列
print(B) #2行3列
G=np.ones((3,2)) #3行2列
print(G)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
B*D  #直接对应元素相乘

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
G.dot(B)  #矩阵想乘

array([[5., 7., 9.],
       [5., 7., 9.],
       [5., 7., 9.]])

In [82]:
#內积
#numpy.inner(a,b)
#np.inner(a, b) = sum(a[:]*b[:])
#np.inner(a, b) = np.tensordot(a, b, axes=(-1,-1))
q = np.arange(6).reshape((2,3))
print(q)
print("\n")
w = np.arange(3)
print(w)
print("\n")
print(np.inner(q,w))
print("\n")
print(np.inner(q,q))

[[0 1 2]
 [3 4 5]]


[0 1 2]


[ 5 14]


[[ 5 14]
 [14 50]]


In [40]:
'''
常用函数
'''
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
#求和
test.sum(axis=0)  #axis指定轴数  0表示跨行（垂直方向） 1表示跨列（水平方向）

array([15, 18, 21, 24, 27])

In [42]:
test.sum(axis=1)

array([10, 35, 60])

In [43]:
#min/max
test.max(axis=1)

array([ 4,  9, 14])

In [44]:
#累和
test.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [55]:
#exp,sqrt,add，substract
np.exp(A)
np.sqrt(A)
K=np.add(A,B)
H=np.subtract(A,B)
H

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [54]:
#寻找假，有假则假
#numpy.all(a, axis=None, out=None, keepdims=<no value>)
#NaN / 正无穷 / 负无穷都是True,因为它们都不等于0
#寻找真，有真则真
#numpy.any(a, axis=None, out=None, keepdims=<no value>)
np.all(A)


True

In [56]:
np.all(H)

False

In [62]:
#向上取整
#np.ceil
#向下取整
#np.floor
#限制上下限
#np.clip(a, a_min, a_max, out=None)
#沿着给定的轴作用函数func1d   返回处理过后的数组
#np.apply_along_axis(func1d, axis, arr, *args, **kwargs)
def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5

In [63]:
t = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
np.apply_along_axis(my_func, 0, t) #跨行，1+7=4

array([4., 5., 6.])

In [65]:
np.apply_along_axis(my_func, 1, t) #跨列 1+3=2

array([2., 5., 8.])

In [68]:
#返回沿着轴最大/小值的索引
#np.argmax(a, axis=None, out=None)
#np.argmin(a, axis=None, out=None)
np.argmax(t,axis=0)  #

array([2, 2, 2], dtype=int64)